# Generated by Django 5.1.7 on 2025-04-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='tipo',
            new_name='hostilidad',
        ),
    ]
