# Generated by Django 5.1.7 on 2025-04-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_rename_tipo_animal_hostilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.CharField(default='img/Animales/default.webp', max_length=200),
            preserve_default=False,
        ),
    ]
