# Generated by Django 5.1.7 on 2025-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_enemigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pueblo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionVariada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='construccion',
            name='imagen',
            field=models.CharField(default='img/Construcciones/default.webp', max_length=200),
            preserve_default=False,
        ),
    ]
