# Generated by Django 5.1.7 on 2025-04-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_pueblo_ubicacionespecifica_ubicacionvariada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
    ]
