# Generated by Django 5.1.7 on 2025-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_arma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=200)),
                ('hambre_normal', models.IntegerField()),
                ('agua_normal', models.IntegerField()),
                ('vida_normal', models.IntegerField()),
                ('energia_normal', models.IntegerField()),
                ('hambre_dificil', models.IntegerField()),
                ('agua_dificil', models.IntegerField()),
                ('vida_dificil', models.IntegerField()),
                ('energia_dificil', models.IntegerField()),
            ],
        ),
    ]
