# Generated by Django 5.1.7 on 2025-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_consumible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
            ],
        ),
    ]
